/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tanity (https://sketchfab.com/tanity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-bike-cb03b0657fbc4693b59194124ba713db
Title: Road Bike
*/

import { useGLTF } from "@react-three/drei";

const Bicycle = (props) => {
  const { nodes, materials } = useGLTF("/models/road_bike.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[122.115, 83.986, -0.003]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.516}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector002_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector002_seatskin_0_1.geometry}
            material={materials["seat.skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector002_seatskin_0_2.geometry}
            material={materials["seat.skin"]}
          />
          <group
            position={[0.068, 11.511, -7.582]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[193.736, 129.51, 193.736]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wheel_left001_wheelblack_0.geometry}
              material={materials["wheel.black"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wheel_left001_wheelorange_0.geometry}
              material={materials["wheel.orange"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wheel_left001_metalblack_0.geometry}
              material={materials["metal.black"]}
            />
          </group>
        </group>
        <group
          position={[88.676, 23.589, 0.024]}
          rotation={[-Math.PI / 2, -0.016, 0]}
          scale={[-100, 100, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle052_metalsilver2_0.geometry}
            material={materials["metal.silver2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle052_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <group
          position={[-109.618, 83.986, -0.003]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.516}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector_seatskin_0_1.geometry}
            material={materials["seat.skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.protector_seatskin_0_2.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <group
          position={[-115.56, 80.073, -0.047]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 66.849, 100]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_left_wheelblack_0.geometry}
            material={materials["wheel.black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_left_wheelorange_0.geometry}
            material={materials["wheel.orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wheel_left_metalblack_0.geometry}
            material={materials["metal.black"]}
          />
        </group>
        <group
          position={[-84.88, 25.297, 0.024]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle051_metalsilver2_0.geometry}
            material={materials["metal.silver2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle051_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <group position={[-41.643, 120.46, -0.166]} scale={6.026}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["1_orangemetal_0"].geometry}
            material={materials["orange.metal"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["1_rama_0"].geometry}
            material={materials.rama}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["1_seatplastic_0"].geometry}
            material={materials["seat.plastic"]}
          />
        </group>
        <group
          position={[-66.535, 228.606, 0]}
          rotation={[-Math.PI / 2, 0.121, 0]}
          scale={30.142}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_wheelorange_0.geometry}
            material={materials["wheel.orange"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <group
          position={[15.677, 78.239, 26.31]}
          rotation={[-Math.PI / 2, -0.628, 0]}
          scale={6.408}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_seatplastic_0.geometry}
            material={materials["seat.plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_lightorange_0.geometry}
            material={materials["light.orange"]}
          />
        </group>
        <group
          position={[-59.249, 48.467, -26.31]}
          rotation={[Math.PI / 2, 0.049, -Math.PI]}
          scale={6.408}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane026_seatplastic_0.geometry}
            material={materials["seat.plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane026_lightorange_0.geometry}
            material={materials["light.orange"]}
          />
        </group>
        <group
          position={[103.522, 148.383, -0.6]}
          rotation={[-2.858, 0, -Math.PI]}
          scale={0.925}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle008_metalsilver_0.geometry}
            material={materials["metal.silver"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle008_metalblack_0.geometry}
            material={materials["metal.black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle008_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <group
          position={[-85.751, 142.742, -0.439]}
          rotation={[-2.873, 0.094, -2.814]}
          scale={[-0.925, 0.925, 0.925]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle035_metalsilver_0.geometry}
            material={materials["metal.silver"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle035_metalblack_0.geometry}
            material={materials["metal.black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle035_seatskin_0.geometry}
            material={materials["seat.skin"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_rama_0.geometry}
          material={materials.rama}
          position={[67.381, 199.255, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[85.193, 204.683, 0.076]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[90.765, 205.623, 0.57]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[68.241, 195.013, 0.016]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle011_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[90.765, 205.745, 0]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle012_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[95.687, 191.183, 0]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle013_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[120.403, 212.835, 0]}
          rotation={[0, 0, 1.145]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[124.038, 209.81, 0]}
          rotation={[0, 0, 1.145]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle015_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[131.461, 215.95, 0]}
          rotation={[0, 0, 1.145]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_Blue_0.geometry}
          material={materials.Blue}
          position={[127.246, 200.066, 0]}
          rotation={[0, 0, 1.145]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[122.237, 191.705, 0]}
          rotation={[0, 0, 1.145]}
          scale={4.127}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle030_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[60.947, 203.37, 0.091]}
          scale={0.575}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle031_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[63.11, 196.916, 0.091]}
          scale={0.575}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle033_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[90.765, 205.623, 0.001]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={0.575}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle034_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[124.08, 211.29, 0]}
          rotation={[-3.057, -0.155, -0.011]}
          scale={[-0.422, 0.422, 0.422]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle036_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[124.08, 211.29, 0]}
          rotation={[-3.057, -0.155, -0.011]}
          scale={[-0.422, 0.422, 0.422]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[116.265, 79.568, -0.147]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle018_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[116.266, 79.564, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle028_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[116.266, 79.564, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1001_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[104.914, 107.111, 4.014]}
          rotation={[-Math.PI / 2, 0.788, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1002_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[111.7, 109.006, -4.309]}
          rotation={[-Math.PI / 2, 1.025, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1003_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[87.074, 85.509, 4.014]}
          rotation={[-Math.PI / 2, -0.192, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1021_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[89.285, 92.198, -4.309]}
          rotation={[-Math.PI / 2, 0.045, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1022_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[94.449, 59.283, 4.014]}
          rotation={[-Math.PI / 2, -1.141, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1023_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[90.295, 64.974, -4.309]}
          rotation={[-Math.PI / 2, -0.904, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1024_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[120.372, 50.063, 4.014]}
          rotation={[Math.PI / 2, -1.04, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1025_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[113.328, 49.923, -4.309]}
          rotation={[Math.PI / 2, -1.277, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1026_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[143.312, 67.082, 4.014]}
          rotation={[Math.PI / 2, -0.04, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1027_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[139.335, 60.72, -4.309]}
          rotation={[Math.PI / 2, -0.293, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1028_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[141.743, 95.005, 4.014]}
          rotation={[Math.PI / 2, 0.937, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1029_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[144.786, 88.169, -4.309]}
          rotation={[Math.PI / 2, 0.685, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1030_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[127.967, 107.158, 4.372]}
          rotation={[-Math.PI / 2, 1.474, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1031_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[129.023, 106.66, -3.951]}
          rotation={[Math.PI / 2, 1.417, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle027_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[-115.468, 79.564, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[-115.468, 79.564, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1004__0.geometry}
          material={materials["spitsi1.004__0"]}
          position={[-126.819, 107.111, 4.014]}
          rotation={[-Math.PI / 2, 0.788, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle020_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-115.468, 79.568, -0.147]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1008_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-119.629, 109.066, -4.309]}
          rotation={[-Math.PI / 2, 1.038, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1006_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-144.66, 85.509, 4.014]}
          rotation={[-Math.PI / 2, -0.192, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1007_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-142.421, 92.255, -4.309]}
          rotation={[-Math.PI / 2, 0.048, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1011_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-137.284, 59.283, 4.014]}
          rotation={[-Math.PI / 2, -1.141, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1012_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-141.469, 65.029, -4.309]}
          rotation={[-Math.PI / 2, -0.902, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1013_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-111.361, 50.063, 4.014]}
          rotation={[Math.PI / 2, -1.04, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1014_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-118.468, 49.93, -4.309]}
          rotation={[Math.PI / 2, -1.279, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1015_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-88.617, 66.665, 4.014]}
          rotation={[Math.PI / 2, -0.056, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1016_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-92.439, 60.672, -4.309]}
          rotation={[Math.PI / 2, -0.295, -Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1017_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-90.171, 95.3, 4.014]}
          rotation={[Math.PI / 2, 0.949, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1018_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-86.956, 88.199, -4.309]}
          rotation={[Math.PI / 2, 0.686, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1019_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-103.767, 107.158, 4.372]}
          rotation={[-Math.PI / 2, 1.474, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1020_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-102.368, 106.496, -3.951]}
          rotation={[Math.PI / 2, 1.404, Math.PI]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.spitsi1005_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-126.819, 107.111, 4.014]}
          rotation={[-Math.PI / 2, 0.788, 0]}
          scale={0.402}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_rama_0.geometry}
          material={materials.rama}
          position={[96.11, 125.146, 0]}
          rotation={[-Math.PI / 2, -0.296, 0]}
          scale={8.546}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle050_rama_0.geometry}
          material={materials.rama}
          position={[1.554, 171.576, 0]}
          rotation={[-Math.PI / 2, 1.372, Math.PI / 2]}
          scale={1.676}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-65.731, 209.988, -0.266]}
          rotation={[0, 0, -0.729]}
          scale={5.303}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-69.788, 219.014, -3.934]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[99.106, 111.148, 111.148]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle037_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-74.175, 216.924, -0.463]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.085}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle038_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-60.66, 216.924, -0.463]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.085}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath002_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-69.689, 219.066, 3.305]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[99.106, 111.148, 111.148]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[-67.229, 223.948, -0.001]}
          rotation={[-Math.PI / 2, 0.121, 0]}
          scale={[30.659, 31.196, 30.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[-92.459, 224.58, -4.196]}
          rotation={[-Math.PI / 2, 0.121, 0]}
          scale={[30.659, 31.196, 30.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[-92.459, 224.58, 3.57]}
          rotation={[-Math.PI / 2, 0.121, 0]}
          scale={[30.659, 31.196, 30.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[-47.809, 222.49, 1.923]}
          rotation={[1.417, 1.043, -3.122]}
          scale={[30.659, 31.196, 30.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_seatplastic_0.geometry}
          material={materials["seat.plastic"]}
          position={[-47.809, 222.49, -2.118]}
          rotation={[1.724, 1.043, -0.02]}
          scale={[-30.659, 31.196, 30.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-56.788, 69.726, 9.463]}
          scale={[10.179, 10.179, 4.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle022_rama_0.geometry}
          material={materials.rama}
          position={[-21.757, 63.216, 0]}
          scale={6.026}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[-21.686, 63.508, 9.894]}
          rotation={[0, 0, -1.096]}
          scale={1.106}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle039_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-19.443, 64.204, 10.846]}
          rotation={[0.012, -0.018, 0.155]}
          scale={5.591}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[-115.348, 79.546, 8.711]}
          rotation={[0, 0, -0.464]}
          scale={1.061}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle040_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-22.305, 81.911, 10.654]}
          scale={1.322}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle041_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-39.376, 68.576, 10.654]}
          rotation={[0, 0, 1.261]}
          scale={1.322}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle042_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-31.879, 48.245, 10.654]}
          rotation={[0, 0, 2.522]}
          scale={1.322}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle043_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-10.486, 48.991, 10.654]}
          rotation={[0, 0, -2.518]}
          scale={1.322}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle044_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-4.366, 69.633, 8.86]}
          rotation={[0, 0, -1.266]}
          scale={1.322}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle026_metalblack_0.geometry}
          material={materials["metal.black"]}
          position={[-26.688, 61.333, -13.258]}
          rotation={[-0.012, 0.018, -2.995]}
          scale={5.591}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[105.947, 165.78, -15.77]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-1.052, 1.052, 1.052]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[105.505, 165.833, 14.568]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={[-0.795, 0.795, 0.795]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle009_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[105.514, 165.774, 0.494]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.643, 0.643, 0.643]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[105.503, 165.768, 11.624]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={3.215}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath001_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[105.518, 168.605, 12.681]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={29.72}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath003_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[105.024, 166.18, -15.74]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={29.72}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath010_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[96.954, 202.847, 8.478]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={29.72}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[-82.207, 160.005, -15.853]}
          rotation={[1.571, 1.23, -Math.PI]}
          scale={1.052}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle032_metalsilver2_0.geometry}
          material={materials["metal.silver2"]}
          position={[-81.793, 159.853, 14.568]}
          rotation={[Math.PI / 2, 1.23, Math.PI / 2]}
          scale={0.795}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle045_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[-81.82, 159.8, 0.958]}
          rotation={[0, 0, 2.801]}
          scale={0.643}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[-81.812, 159.79, 12.089]}
          rotation={[-Math.PI / 2, 0.341, -Math.PI / 2]}
          scale={[-3.215, 3.215, 3.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath007_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[-81.296, 159.932, -16.18]}
          rotation={[-Math.PI / 2, 0.341, -Math.PI / 2]}
          scale={[-29.72, 29.72, 29.72]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath011_seatskin_0.geometry}
          material={materials["seat.skin"]}
          position={[29.403, 184.737, 1.336]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={29.72}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath006_metalsilver_0.geometry}
          material={materials["metal.silver"]}
          position={[-80.124, 161.012, 13.058]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={29.72}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/road_bike.glb");

export default Bicycle;
