/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kero.Los (https://sketchfab.com/Kero.Los)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-mug-8ef6106a071845368d94bb7bd827bfdb
Title: Coffee Mug
*/

import { useGLTF } from "@react-three/drei";

const Coffee = (props) => {
  const { nodes, materials } = useGLTF("/models/coffee.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.909}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cup_Plate_Coffee_Plate_MAT_0.geometry}
              material={materials.Coffee_Plate_MAT}
            />
            <group position={[0, 0, 0.085]} scale={0.085}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Coffee_Cup_Coffee_Cup_MAT_0.geometry}
                material={materials.Coffee_Cup_MAT}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Coffee_Coffee_Rosetta_Latte_MAT_0.geometry}
                material={materials.Coffee_Rosetta_Latte_MAT}
                scale={11.834}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/coffee.glb");

export default Coffee;
