/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: stealth86 (https://sketchfab.com/stealth86)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telephone-019372d297fc480ca7766cb1f3fec048
Title: Telephone
*/

import { useGLTF } from "@react-three/drei";

const Telephone = (props) => {
  const { nodes, materials } = useGLTF("/models/telephone.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[0, 287.429, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wire_Phone_0.geometry}
            material={materials.Phone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wire_Feet_0.geometry}
            material={materials.Feet}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Handle_Handle_0.geometry}
          material={materials.Handle}
          position={[-147.72, 657.27, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Phone_Phone_0.geometry}
          material={materials.Phone}
          position={[0, 287.429, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={251.658}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Numberpad_Dial_0.geometry}
          material={materials.Dial}
          position={[336.051, 344.724, -0.022]}
          rotation={[-1.569, 0.69, -0.169]}
          scale={299.353}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Limiter_Pin_0.geometry}
          material={materials.material}
          position={[431.224, 321.429, -207.656]}
          rotation={[-0.18, -0.356, -0.587]}
          scale={23.903}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dial_Center_0.geometry}
          material={materials.Center}
          position={[364.428, 378.939, -0.501]}
          rotation={[-1.548, 0.686, -0.008]}
          scale={105.55}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Feet001_Feet_0.geometry}
          material={materials.Feet}
          position={[0, 289.312, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={251.658}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/telephone.glb");

export default Telephone;
