/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: holgcool (https://sketchfab.com/holgcool)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toolbox-9df47cc2d6174d2b86c22cdfa4b423aa
Title: Toolbox
*/

import { useGLTF } from "@react-three/drei";

const Toolbox = (props) => {
  const { nodes, materials } = useGLTF("/models/toolbox.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_a_LP_box_a_0.geometry}
          material={materials.box_a}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/toolbox.glb");

export default Toolbox;
