/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zuckergelee (https://sketchfab.com/knorke)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/travelers-desk-lowpoly-0a9d39f8926d480bb7d003514de88877
Title: Traveler's desk (lowpoly)
*/

import { useGLTF } from "@react-three/drei";

const ExplorerRoom = (props) => {
  const { nodes, materials } = useGLTF("/models/explorer-room.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/explorer-room.glb");

export default ExplorerRoom;
