/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shadowkillering (https://sketchfab.com/shadowkillering)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-desk-cdde895551904b63abcdf93aba05936a
Title: Stylized desk
*/

import { useGLTF } from "@react-three/drei";

const ReaderRoom = (props) => {
  const { nodes, materials } = useGLTF("/models/reader-room.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-66.805, 83.559, -12.608]}
        rotation={[2.946, -0.079, 1.56]}
        scale={[66.245, 68.556, 88.591]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book004_Desk_Objects_0.geometry}
          material={materials.Desk_Objects}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.marque_page1_Desk_Objects_0.geometry}
          material={materials.Desk_Objects}
          position={[-0.019, -0.179, -0.382]}
          rotation={[2.734, -1.472, 1.229]}
          scale={[1.458, 1.133, 1.506]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Nappe_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-26.603, 70.287, -59.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["porte-lettres_Desk_Objects_0"].geometry}
        material={materials.Desk_Objects}
        position={[-78.479, 76.69, -5.642]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hourglass_TransparentObjects_0.geometry}
        material={materials.TransparentObjects}
        position={[-72.786, 70.202, -30.17]}
        rotation={[-Math.PI / 2, 0, -0.57]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot_3_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-71.984, 70.299, -44.23]}
        rotation={[-Math.PI / 2, 0, -0.158]}
        scale={[140.151, 121.695, 135.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot_1_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-64.778, 70.128, -52.17]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[156.484, 156.484, 161.929]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot_2_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-67.083, 70.29, -89.695]}
        rotation={[-Math.PI / 2, 0, 0.341]}
        scale={[98.397, 100, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottle_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-56.331, 70.117, -108.503]}
        rotation={[-Math.PI / 2, 0, -0.232]}
        scale={[93.71, 86.788, 100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_TransparentObjects_0.geometry}
        material={materials.TransparentObjects}
        position={[-60.604, 70.299, -124.778]}
        rotation={[-Math.PI / 2, 0, 1.689]}
        scale={[243.378, 211.328, 325.182]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.loupe_TransparentObjects_0.geometry}
        material={materials.TransparentObjects}
        position={[-69.475, 62.623, -102.889]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sand_Material_0.geometry}
        material={materials.Material}
        position={[-72.786, 70.202, -30.17]}
        rotation={[-Math.PI / 2, 0, -0.57]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-6.874, 75.852, -17.43]}
        rotation={[-1.652, -0.021, 0.309]}
        scale={152.224}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_TransparentObjects_0.geometry}
        material={materials.TransparentObjects}
        position={[-10.478, 83.439, -113.504]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheets_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-16.927, 72.877, -10.652]}
        rotation={[-1.587, 0.045, -0.156]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plume_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-68.611, 75.806, -52.462]}
        rotation={[-Math.PI / 2, -0.594, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-70.039, 75.015, 6.574]}
        rotation={[-1.771, 0, 0.018]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheets001_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-48.742, 72.877, -66.047]}
        rotation={[-1.519, 0.008, -1.87]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre001_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-68.272, 71.036, -3.723]}
        rotation={[-3.13, -0.017, 0.004]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre002_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-65.113, 71.531, -2.942]}
        rotation={[-3.13, -0.275, 0.007]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre003_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-68.272, 72.021, -3.723]}
        rotation={[-3.04, -0.255, 0.081]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre004_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-65.113, 72.515, -2.942]}
        rotation={[-3.017, -0.512, 0.093]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre005_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-68.272, 71.96, -3.723]}
        rotation={[-3.129, -0.016, 0.09]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre006_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-65.113, 73.701, -2.942]}
        rotation={[-3.105, -0.273, 0.097]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre007_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-68.272, 72.945, -3.723]}
        rotation={[-3.018, -0.245, 0.17]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lettre008_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-65.113, 74.686, -2.942]}
        rotation={[-2.969, -0.499, 0.191]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheets002_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-32.629, 72.877, -28.025]}
        rotation={[-1.543, 0.006, -2.108]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheets003_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-13.788, 72.146, -97.12]}
        rotation={[-1.584, -0.005, -0.269]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book001_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-11.713, 79.892, -105.63]}
        rotation={[Math.PI / 2, 0, -0.182]}
        scale={[76.698, 79.341, 76.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_open_LP_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[7.521, 69.936, -52.18]}
        rotation={[-Math.PI / 2, 0.07, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book003_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[-12.258, 70.881, -106.217]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[95.835, 99.138, 95.835]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.marque_page2_Desk_Objects_0.geometry}
        material={materials.Desk_Objects}
        position={[7.062, 72.937, -31.154]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Desk_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-33.538, 0, -59.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Drawers_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-42.978, 0, -59.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handles001_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-42.978, 0, -59.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handles002_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-42.978, -11.048, -59.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handles003_DeskBody_0.geometry}
        material={materials.DeskBody}
        position={[-42.978, -6.396, -168.567]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
};

useGLTF.preload("/models/reader-room.glb");

export default ReaderRoom;
